server:
  port: 8085

logging:
  file:
    path: logs

security:
  jwt:
    secret: ${SPRING_JWT_TOKEN:mZfpLztVGV1ROkxXpXNRwFdoIUuJArRI4k+ouB+Hr4rfydy7hGfMY0+tnXJkmDuMgQkPQ1O6s5VUg5LoepC42g==}
    expiration: ${SPRING_JWT_EXPIRATION:7200000}

spring:
  data:
    mongodb:
      auto-index-creation: true
  jackson:
    default-property-inclusion: NON_NULL
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /actuator
      cors:
        allowed-origins: "*"
        allowed-methods: GET,POST,PUT,DELETE
  endpoint:
    health:
      show-details: always
